#!/usr/bin/env python3

# This file is part of Openplotter.
# Copyright (C) 2019 by sailoog <https://github.com/sailoog/openplotter>
#                     e-sailing <https://github.com/e-sailing/openplotter>
# Openplotter is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# any later version.
# Openplotter is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openplotter. If not, see <http://www.gnu.org/licenses/>.

import sys, os, subprocess
if "DISPLAY" in os.environ:
	pass
else:
	os.environ["DISPLAY"] = ':0'
import wx
from classes.language import Language
from classes.conf import Conf


class MyFrame(wx.Frame):
	def __init__(self, parent):
		conf = Conf()
		Language(conf)

		this_pid = str(os.getpid())
		old_pid = ''
		process_info = subprocess.check_output(['ps','aux']).decode().split('\n')
		for i in process_info:
			if '/message ' in i:
				if this_pid in i:
					pass
				else:
					i_s = i.split(' ')
					old_pid = int(i[9:15])
					subprocess.call(['kill', '-15', str(old_pid)])

		text=sys.argv[1]
		if len(text)<50:
			text = (text+'                                                  ')[:50]

		wx.Frame.__init__(self, parent)
		dlg = wx.MessageDialog(None, text, _('Action Message'))
		dlg.ShowModal()
		sys.exit()

app = wx.App(False)
frame = MyFrame(None)
app.MainLoop()
